# Project : Graph Sceleton
# Course	: Functional and Logic Programming
# Author  : Peter Grofcik
# Login   : xgrofc00
# Year    : 2020

all:
	swipl -o flp20-log -q -g main -t true -c main.pl
clean:
	rm flp20-log tests/test*.out
