# Project : simplify-bkg
# Author  : Peter Grofcik
# Login   : xgrofc00
# Year    : 2020

all: simplify

simplify:
	ghc src/Syntax.hs src/First.hs src/Second.hs src/Simplify.hs -o simplify-bkg

clean:
	 rm src/*.hi src/*.o simplify-bkg
